---
title: "Week 10 - Data Science Lifecycle"
---

<script defer data-domain="rbtl-fs22.github.io/website" src="https://plausible.io/js/plausible.js"></script>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction

Now that you have your data, we will set you up to start working collaboratively on your report. This homework is about familiarising yourself with the report template. You will also read about exploratory data visualisation, which is our topic for next week. 

## Prerequisites

We assume that you have:

1. Collected your data 

## Learning Objectives

1. Learners can describe the four main aesthetic mappings that can be used to visualise data using the ggplot2 R Package
2. Learners can control the colour scaling applied to a plot using colour as an aesthetic mapping
3. Learners can compare three different geoms and their use case
4. Learners can apply a theme to control font types and sizes within a plot

## Terminology {#terminology}

# Exercises

## Exercise 1 - Application Exercise

1. Open the repo from class and `pull` changes from remote repository; A solutions file `ae-10a-lifecycle-solutions.qmd` will be added; Ensure that your script `ae-10a-lifecycle.qmd` is complete and renders without errors
2. Add, Commit, Push all changes to GitHub with the commit message "Render exercise 10a without errors"
3. Complete all tasks in Application Exercise 10 - Data Science Lifecycle (`ae-10b-lifecycle.qmd` file) 
4. Ensure that `ae-10b-lifecycle.qmd` renders without errors
4. Add, Commit, Push all changes to GitHub with the commit message "Complete tasks of exercise 10b"

## Exercise 2 -


## Exercise 3 - 


## Exercise 4 - Get started with your analysis

1. Open your research-project-template team repo on the RStudio Cloud
2. From the file manager (bottom right window), open your assigned  "Results & Discussions" file
3. Add a 1st level heading titled "Data import"
4. Add a code-chunk below the first level heading
5. Load the `readr` R package using the `library()` function
5. Render the file without any errors
6. Add, commit, push your changes back to GitHub

## Exercise 5 - Read R4DS and practice


1. Open the rbtl-fs22 GitHub organisation and clone the notebook repo with your name (notebook-[GITHUB_USERNAME]) to the rbtl-fs22 workspace on RStudio Cloud.
2. Read Chapter Introduction of R4DS: https://r4ds.had.co.nz/explore-intro.html 
3. Read Chapter Data Visualisation (3.1 to 3.6) of R4DS: https://r4ds.had.co.nz/data-visualisation.html

**Note: If you use the notebook to take notes while working through R4DS, then use the Render, Add, Commit, Push workflow every now and then to push your changes back to GitHub and keep your remote repository in sync with your local repository.**




